### ISSUE TITLE
IE and Edge round letter-spacing to the nearest hundreth, so actual letter spacing is off by 0.1px

### ISSUE THREAD

**Issue by awikkerink** [BrightspaceUI/typography#72]
```css
.d2l-typography,
.d2l-typography .d2l-body-standard,
.vui-typography,
.vui-typography .d2l-body-standard {
	color: var(--d2l-color-ferrite);
	display: block;
	font-family: 'Lato', 'Lucida Sans Unicode', 'Lucida Grande', sans-serif;
	font-size: 1rem;
	font-weight: 300;
	line-height: 1.5;
	letter-spacing: 0.015rem;
	@apply(--d2l-font-custom);
}
```
In IE/Edge inspector:
```css
:not([style-scope]):not(.style-scope).d2l-typography, .d2l-typography :not([style-scope]):not(.style-scope).d2l-body-standard, :not([style-scope]):not(.style-scope).vui-typography, .vui-typography :not([style-scope]):not(.style-scope).d2l-body-standard {
    color: #565a5c;
    display: block;
    font-family: "Lato", "Lucida Sans Unicode", "Lucida Grande", sans-serif;
    font-size: 1rem;
    font-weight: 300;
    line-height: 1.5;
    letter-spacing: 0.01rem;
}
```
